//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quejas_Proyecto.context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quejasEntities : DbContext
    {
        public quejasEntities()
            : base("name=quejasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comercio> comercios { get; set; }
        public virtual DbSet<departamento> departamentoes { get; set; }
        public virtual DbSet<municipio> municipios { get; set; }
        public virtual DbSet<queja> quejas { get; set; }
        public virtual DbSet<region> regions { get; set; }
        public virtual DbSet<sucursal> sucursals { get; set; }
    }
}
