//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quejas_Proyecto.context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class queja
    {
        public int idqueja { get; set; }
        public int idsucursal { get; set; }
        [Display(Name = "Queja")]
        public string queja1 { get; set; }
        [Display(Name = "Fecha")]
        public Nullable<System.DateTime> fecha_queja { get; set; }
    
        public virtual sucursal sucursal { get; set; }
    }
}
